games = ['Rimworld', 'Red Dead 2', 'COTL']
second_games = ['Schedule I', 'KOA', 'Autoforge']
second_games.insert(0, 'Grounded')
second_games.insert(1, "Minecraft")
second_games.append("Castle Crashers")
print(f"{games[0]} sounds fun right about now!")
print(f"Despite {games[0]} soundin fun, It's been a while since I played {second_games[5]}!")
second_games.pop(0)
print(f"Sorry, {second_games[0]}, I'll play you later")
second_games.pop(0)
print(f"Sorry, {second_games[1]}, I'll play you later")
second_games.pop(1)
print(f"Sorry, {second_games[0]}, I'll play you later")
second_games.pop(0)
print(f"Sorry, {second_games[0]}, I'll play you later")
second_games.pop(0)
print(f"Sorry, {second_games[0]}, I'll play you later")
games.pop(1)
print(f"Sorry, {games[1]}, I'll play you later")
games.pop(1)
print(f"Sorry, {games[0]}, I'll play you later")
print(games)
print(second_games)
print(f"I have {len(games) + len(second_games)} games to play!")
