guest = ['lindsey', 'mark', 'bob']
backup_list = ['Will', 'Tom', "Frank"]
backup_list.insert(0, "Domonic")
backup_list.insert(3, "Rob")
backup_list.append("Milly")
print(f"{guest[0]}, You're invited")
print(f"{guest[2]}, You're invited")
print(f"{guest[1]} couldnt make it so that means that {backup_list[0]} is invited in his stead! So that means")
print(f"{guest[0]}, You're invited")
print(f"{guest[2]}, You're invited")
print(f"{backup_list[0]}, We have a bigger table, You're invited")
print(f"{backup_list[3]}, We have a bigger table, You're invited")
print(f"{backup_list[5]}, We have a bigger table, You're invited")
print("We only have space for 2 since the table wont arrive on time")
backup_list.pop(0)
print(f"Sorry, {backup_list[0]}, We have no room")
backup_list.pop(1)
print(f"Sorry, {backup_list[2]}, We have no room")
backup_list.pop(2)
print(f"Sorry, {backup_list[1]}, We have no room")
backup_list.pop(0)
print(f"Sorry, {backup_list[0]}, We have no room")
guest.pop(1)
print(f"Sorry, {guest[1]}, We have no room")
print(guest)
print(backup_list)
